#!/usr/bin/env bash 

set -e # halt script on error

bundle install
bundle exec jekyll build
bundle exec htmlproofer  --disable-external --assume-extension --allow-hash-href --empty-alt-ignore ./_site 
